model: efficientdet_d0_128 
dataset: ours
batch_size: 256
amp: true
lr: .008 
sync-bn: true
opt: fusedmomentum 
warmup-epochs: 1 
model-ema: true
model-ema-decay: 0.9966 
epochs: 50 
num-classes: 12 
pretrained: true