model: tf_efficientdet_lite0_96 
dataset: ours
batch_size: 256
amp: true
lr: .01 
sync_bn: true
opt: fusedmomentum 
warmup_epochs: 1 
decay_ephocs: 1
cooldown_epochs: 1
patience_epochs: 1
model_ema: true
model_ema_decay: 0.9966 
epochs: 20 
num_classes: 12 
pretrained: false